// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Leal from "../../../index.js";

export declare namespace WebhookSubscriptionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * A webhook subscription tells Leal to POST a JSON payload to your URL whenever an event
 * happens in the store, so you don't have to poll. Subscribe to a list of `events`, or to
 * `["*"]` for every event (including ones added later). The full guide, with payload examples and
 * signature verification code, is at https://www.getleal.com/developers/webhooks.
 *
 * Events
 *
 * - `customer.created`: A customer joined the loyalty program.
 * - `customer.updated`: A customer's name, email, phone, birthday, metadata or marketing and SMS consent changed.
 * - `customer_card.created`: A customer was issued a loyalty card. Includes the Apple Wallet and Google Wallet links.
 * - `stamp.earned`: Stamps were added to a customer's card, from a scan, the API or an adjustment.
 * - `stamp.removed`: Stamps were taken off a customer's card by an adjustment. Redeeming a reward sends reward.redeemed instead.
 * - `reward.unlocked`: A customer now has enough stamps to redeem a reward. Sent once per reward, when the threshold is crossed.
 * - `reward.redeemed`: A customer redeemed a reward.
 *
 * Payload
 *
 * Each delivery is an envelope: `{"id": "evt_...", "type": "stamp.earned", "timestamp": "...",
 * "account_id": 1, "data": {...}}`. `id` is unique per event and stays the same across
 * retries, so use it to ignore duplicates. `customer.updated` also carries
 * `previous_attributes` with the old values of the fields that changed.
 *
 * Subscriptions created from Zapier (and all subscriptions created before signing was
 * introduced) use `payload_format: "flat"`, which sends the `data` object on its own. The
 * event name is still available in the `Leal-Event` header. A flat subscription has exactly
 * one event.
 *
 * Older integrations send and read a single `event` string. That still works: `event` sets
 * `events` to that one event, and responses include `event` whenever there is exactly one.
 *
 * Verifying requests
 *
 * Every delivery is signed using the Standard Webhooks scheme (https://www.standardwebhooks.com)
 * with the subscription's `secret`, via the `webhook-id`, `webhook-timestamp` and
 * `webhook-signature` headers. Any Standard Webhooks library can verify it.
 *
 * Retries
 *
 * Respond with any 2xx status within 10 seconds. Anything else, or no response, is retried
 * with increasing delays, up to 10 attempts over about four hours.
 * Responding `410 Gone` deletes the subscription. A subscription that has not had a
 * successful delivery for 3 days is disabled
 * (`enabled: false`, `disabled_reason: "failing"`); re-enable it with `PATCH` once fixed.
 */
export class WebhookSubscriptionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhookSubscriptionsClient.Options>;

    constructor(options: WebhookSubscriptionsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns every webhook subscription for the store, oldest first. Signing secrets are not included; fetch a single subscription to read its secret.
     *
     * @param {Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
     *         account_id: 1
     *     })
     */
    public getApiV1AccountsAccountIdWebhookSubscriptions(
        request: Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(
            this.__getApiV1AccountsAccountIdWebhookSubscriptions(request, requestOptions),
        );
    }

    private async __getApiV1AccountsAccountIdWebhookSubscriptions(
        request: Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem[]>> {
        const { account_id: accountId, event } = request;
        const _queryParams: Record<string, unknown> = {
            event,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/accounts/{account_id}/webhook_subscriptions",
        );
    }

    /**
     * Subscribes a URL to one or more events. The response includes the signing `secret`; store it to
     * verify deliveries. The URL must be publicly reachable over https.
     *
     * Events: `customer.created`, `customer.updated`, `customer_card.created`, `stamp.earned`, `stamp.removed`, `reward.unlocked`, `reward.redeemed`, or `*` for all of them.
     *
     * @param {Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.UnprocessableEntityError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
     *         account_id: 1,
     *         target_url: "target_url"
     *     })
     */
    public postApiV1AccountsAccountIdWebhookSubscriptions(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__postApiV1AccountsAccountIdWebhookSubscriptions(request, requestOptions),
        );
    }

    private async __postApiV1AccountsAccountIdWebhookSubscriptions(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsResponse>> {
        const { account_id: accountId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 422:
                    throw new Leal.UnprocessableEntityError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/accounts/{account_id}/webhook_subscriptions",
        );
    }

    /**
     * Returns a single subscription, including its signing secret and the result of the most recent delivery.
     *
     * @param {Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
     *         account_id: 1,
     *         id: 1
     *     })
     */
    public getApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getApiV1AccountsAccountIdWebhookSubscriptionsId(request, requestOptions),
        );
    }

    private async __getApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse>> {
        const { account_id: accountId, id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/accounts/{account_id}/webhook_subscriptions/{id}",
        );
    }

    /**
     * Stops deliveries and deletes the subscription. This cannot be undone.
     *
     * @param {Leal.DeleteApiV1AccountsAccountIdWebhookSubscriptionsIdRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
     *         account_id: 1,
     *         id: 1
     *     })
     */
    public deleteApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.DeleteApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__deleteApiV1AccountsAccountIdWebhookSubscriptionsId(request, requestOptions),
        );
    }

    private async __deleteApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.DeleteApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { account_id: accountId, id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/accounts/{account_id}/webhook_subscriptions/{id}",
        );
    }

    /**
     * Changes the URL, events, label or payload format, or turns the subscription off and on. Re-enabling a subscription that was disabled for failing clears its failure state.
     *
     * @param {Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.UnprocessableEntityError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
     *         account_id: 1,
     *         id: 1
     *     })
     */
    public patchApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__patchApiV1AccountsAccountIdWebhookSubscriptionsId(request, requestOptions),
        );
    }

    private async __patchApiV1AccountsAccountIdWebhookSubscriptionsId(
        request: Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse>> {
        const { account_id: accountId, id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.PatchApiV1AccountsAccountIdWebhookSubscriptionsIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 422:
                    throw new Leal.UnprocessableEntityError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/accounts/{account_id}/webhook_subscriptions/{id}",
        );
    }

    /**
     * Replaces the subscription's signing secret. Deliveries are signed with the new secret straight away, so update your receiver at the same time.
     *
     * @param {Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret({
     *         account_id: 1,
     *         id: 1
     *     })
     */
    public postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret(request, requestOptions),
        );
    }

    private async __postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse>> {
        const { account_id: accountId, id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions/${core.url.encodePathParam(id)}/rotate_secret`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecretResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/accounts/{account_id}/webhook_subscriptions/{id}/rotate_secret",
        );
    }

    /**
     * Immediately sends a signed `webhook.test` event to the subscription's URL and reports what
     * happened, so you can check your endpoint and signature verification without waiting for real
     * activity. Test events are not retried and do not count towards disabling the subscription.
     *
     * @param {Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestRequest} request
     * @param {WebhookSubscriptionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Leal.UnauthorizedError}
     * @throws {@link Leal.NotFoundError}
     * @throws {@link Leal.GoneError}
     * @throws {@link Leal.TooManyRequestsError}
     * @throws {@link errors.LealError}
     * @throws {@link errors.LealTimeoutError}
     *
     * @example
     *     await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
     *         account_id: 1,
     *         id: 1
     *     })
     */
    public postApiV1AccountsAccountIdWebhookSubscriptionsIdTest(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): core.HttpResponsePromise<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__postApiV1AccountsAccountIdWebhookSubscriptionsIdTest(request, requestOptions),
        );
    }

    private async __postApiV1AccountsAccountIdWebhookSubscriptionsIdTest(
        request: Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestRequest,
        requestOptions?: WebhookSubscriptionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse>> {
        const { account_id: accountId, id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LealEnvironment.Production,
                `api/v1/accounts/${core.url.encodePathParam(accountId)}/webhook_subscriptions/${core.url.encodePathParam(id)}/test`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Leal.PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Leal.UnauthorizedError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 404:
                    throw new Leal.NotFoundError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 410:
                    throw new Leal.GoneError(_response.error.body as Leal.Error_, _response.rawResponse);
                case 429:
                    throw new Leal.TooManyRequestsError(_response.error.body as Leal.Error_, _response.rawResponse);
                default:
                    throw new errors.LealError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/accounts/{account_id}/webhook_subscriptions/{id}/test",
        );
    }
}
