// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         location: {
 *             address: "address",
 *             name: "name"
 *         }
 *     }
 */
export interface CreateLocationsRequest {
    /** Parent store ID */
    account_id: number;
    location: CreateLocationsRequest.Location;
}

export namespace CreateLocationsRequest {
    export interface Location {
        /** Full street address – automatically geocoded to lat/lng */
        address: string;
        /** Location name (e.g. 'High Street Branch') */
        name: string;
    }
}
