// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1
 *     }
 */
export interface ListLocationsRequest {
    /** Parent store ID */
    account_id: number;
}
