// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1,
 *         location: {}
 *     }
 */
export interface UpdateLocationsRequest {
    /** Parent store ID */
    account_id: number;
    /** Location ID */
    id: number;
    location: UpdateLocationsRequest.Location;
}

export namespace UpdateLocationsRequest {
    export interface Location {
        /** Full street address – automatically geocoded to lat/lng */
        address?: string | undefined;
        /** Location name */
        name?: string | undefined;
    }
}
