// This file was auto-generated by Fern from our API Definition.

export interface UpdateCardsResponse {
    /** ISO 8601 timestamp when the card was archived, or null if active */
    archived_at: string;
    /** Up to two extra front-of-pass fields */
    auxiliary_fields: string[];
    /** Hex colour for the card background (e.g. '#6B4226') */
    card_color: string;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Number of customer card instances issued */
    customer_cards_count: number;
    /** ISO 8601 timestamp when the card expires, or null if it does not expire */
    expires_at: string;
    /** Optional header text displayed on the card */
    header_text: string;
    /** Unique card ID */
    id: number;
    /** Number of stamps pre-filled on new customer cards (0 to stamps_required - 1) */
    initial_stamps: number;
    /** Card name (e.g. 'Coffee Loyalty Card') */
    name: string;
    /** Number of rewards defined for this card */
    rewards_count: number;
    /** Whether wallet passes show the member name field */
    show_member_field: boolean;
    /** Whether wallet passes show the stamps-to-reward field */
    show_stamps_to_reward_field: boolean;
    /** Hex colour for stamp backgrounds */
    stamp_background_color: string;
    /** Hex colour for stamp icons */
    stamp_color: string;
    /** Icon used for stamps (e.g. 'coffee', 'heart', 'star') */
    stamp_icon: string;
    /** Number of stamps needed to complete the card (1–21) */
    stamps_required: number;
    /** Hex colour for the strip (when strip_type is 'color') */
    strip_color: string;
    /** Preset strip image identifier (when strip_type is 'preset') */
    strip_preset: string;
    /** Strip image type: 'color', 'image', or 'preset' */
    strip_type: string;
    /** Hex colour for card text */
    text_color: string;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
