// This file was auto-generated by Fern from our API Definition.

export interface ListCustomerCardsResponseItem {
    /** Link to add or view the pass in Apple Wallet */
    apple_wallet_url: string;
    /** Loyalty card template ID */
    card_id: number;
    /** Name of the loyalty card */
    card_name: string;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Link to add or view the pass in Google Wallet */
    google_wallet_url: string;
    /** Customer card ID */
    id: number;
    /** ISO 8601 timestamp the card was issued */
    issued_at: string;
    /** Whether the wallet pass has been installed */
    pass_installed: boolean;
    /** Completion towards the next reward, 0 to 100 */
    progress_percentage: number;
    /** Stamps collected so far */
    stamps_count: number;
    /** Stamps still needed to complete the card */
    stamps_remaining: number;
    /** Current state of the customer card */
    status: string;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
    /** Public identifier used in wallet pass URLs */
    uuid: string;
}
