// This file was auto-generated by Fern from our API Definition.

export interface RedeemCustomerCardsResponse {
    redemption: RedeemCustomerCardsResponse.Redemption;
    /** True when the reward was redeemed */
    success: boolean;
}

export namespace RedeemCustomerCardsResponse {
    export interface Redemption {
        /** Redemption ID */
        id: number;
        /** ISO 8601 timestamp of the redemption */
        redeemed_at: string;
        /** Reward that was redeemed */
        reward_id: number;
        /** Display name of the reward */
        reward_name: string;
        /** Stamps left on the card afterwards */
        stamps_remaining: number;
        /** Stamps deducted from the card */
        stamps_spent: number;
    }
}
