// This file was auto-generated by Fern from our API Definition.

export interface GetApiV1AccountsAccountIdWebhookSubscriptionsIdResponse {
    /** Parent store ID */
    account_id: number;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Your own label for the subscription */
    description: string;
    /** ISO 8601 time the subscription was disabled */
    disabled_at: string;
    /** `disabled_by_user`, `failing` or `blocked_address` */
    disabled_reason: string;
    /** Whether events are being delivered */
    enabled: boolean;
    /** The event, when there is exactly one (kept for older integrations) */
    event: string;
    /** Events delivered to this URL, or `["*"]` for every event */
    events: string[];
    /** Unique subscription ID */
    id: number;
    /** ISO 8601 time of the most recent delivery attempt */
    last_delivery_at: string;
    /** Why the most recent attempt failed */
    last_delivery_error: string;
    /** HTTP status your URL returned on the most recent attempt */
    last_delivery_status: number;
    /** `envelope` (default) or `flat` (the bare data object, used by Zapier) */
    payload_format: string;
    /** Signing secret (`whsec_...`). Use it to verify the `webhook-signature` header. */
    secret: string;
    /** URL that receives the POST requests */
    target_url: string;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
