// This file was auto-generated by Fern from our API Definition.

export interface PostApiV1AccountsAccountIdWebhookSubscriptionsIdTestResponse {
    /** True when your URL responded with a 2xx status */
    delivered: boolean;
    /** Why the delivery failed */
    error: string;
    /** The `webhook-id` of the test event */
    event_id: string;
    /** HTTP status your URL returned */
    status: number;
}
