// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         customer_id: 1
 *     }
 */
export interface ListCustomerCardsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Customer ID */
    customer_id: number;
}
