// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         customer_id: 1,
 *         id: 1,
 *         stamps: 1
 *     }
 */
export interface StampCustomerCardsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Customer ID */
    customer_id: number;
    /** Customer card ID */
    id: number;
    /** When true, stamp changes bypass notifications */
    skip_notifications?: boolean;
    /** Number of stamps to add (e.g. 1, 3) */
    stamps: number;
}
