// This file was auto-generated by Fern from our API Definition.

/**
 * A JSON error payload. Agents should read `error` for a human readable summary and `errors` for per field validation messages when present.
 */
export interface Error_ {
    /** Human readable description of what went wrong. */
    error?: string | undefined;
    /** Validation messages, either a list of strings or an object keyed by field name. */
    errors?: Error_.Errors | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace Error_ {
    /**
     * Validation messages, either a list of strings or an object keyed by field name.
     */
    export type Errors = string[] | Record<string, string[]>;
}
