// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         poster: {
 *             card_id: 1
 *         }
 *     }
 */
export interface CreatePostersRequest {
    /** Store (account) ID */
    account_id: number;
    poster: CreatePostersRequest.Poster;
}

export namespace CreatePostersRequest {
    export interface Poster {
        /** Whether the poster is active (defaults to true) */
        active?: boolean | undefined;
        /** ID of the loyalty card this poster links to */
        card_id: number;
        /** Which contact fields appear on the public signup form */
        contact_collection_mode?: string | undefined;
        /** Minimum customer age required for signup. Requires require_birthday to be true. */
        minimum_age?: number | undefined;
        /** Print size – one of: a4, a5, a6, letter */
        paper_size?: string | undefined;
        /** Primary brand color as a hex string (e.g. '#FF5733') */
        primary_color?: string | undefined;
        /** Whether date of birth is required on the public signup form */
        require_birthday?: boolean | undefined;
        /** Whether email is required when it is collected */
        require_email?: boolean | undefined;
        /** Whether phone number is required when it is collected */
        require_phone?: boolean | undefined;
        /** Secondary brand color as a hex string */
        secondary_color?: string | undefined;
        /** Text color as a hex string */
        text_color?: string | undefined;
        /** Headline text displayed on the poster */
        title?: string | undefined;
    }
}
