// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1,
 *         poster: {}
 *     }
 */
export interface UpdatePostersRequest {
    /** Store (account) ID */
    account_id: number;
    /** Poster ID */
    id: number;
    poster: UpdatePostersRequest.Poster;
}

export namespace UpdatePostersRequest {
    export interface Poster {
        /** Whether the poster is active */
        active?: boolean | undefined;
        /** Which contact fields appear on the public signup form */
        contact_collection_mode?: string | undefined;
        /** Minimum customer age required for signup. Requires require_birthday to be true. */
        minimum_age?: number | undefined;
        /** Print size – one of: a4, a5, a6, letter */
        paper_size?: string | undefined;
        /** Primary brand color as a hex string */
        primary_color?: string | undefined;
        /** Whether date of birth is required on the public signup form */
        require_birthday?: boolean | undefined;
        /** Whether email is required when it is collected */
        require_email?: boolean | undefined;
        /** Whether phone number is required when it is collected */
        require_phone?: boolean | undefined;
        /** Secondary brand color as a hex string */
        secondary_color?: string | undefined;
        /** Text color as a hex string */
        text_color?: string | undefined;
        /** Headline text displayed on the poster */
        title?: string | undefined;
    }
}
