// This file was auto-generated by Fern from our API Definition.

export interface UpdateRewardsResponse {
    /** Parent store ID */
    account_id: number;
    /** Whether the reward can currently be redeemed */
    active: boolean;
    /** ID of the loyalty card this reward belongs to */
    card_id: number;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Longer description of the reward */
    description: string;
    /** Unique reward ID */
    id: number;
    /** Display name of the reward */
    name: string;
    /** Display order */
    position: number;
    /** Stamps needed before the reward can be redeemed */
    stamps_required: number;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
