// This file was auto-generated by Fern from our API Definition.

export interface ListCustomersResponse {
    /** The customers on this page */
    customers: string[];
    pagination: ListCustomersResponse.Pagination;
}

export namespace ListCustomersResponse {
    export interface Pagination {
        /** Total customers matching the query */
        count: number;
        /** Customers per page */
        items: number;
        /** Current page number */
        page: number;
        /** Total number of pages */
        pages: number;
    }
}
