// This file was auto-generated by Fern from our API Definition.

export interface UpdateCustomersResponse {
    /** Parent store ID */
    account_id: number;
    /** Birthday as YYYY-MM-DD */
    birthday: string;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Cards this customer is enrolled on */
    customer_cards: string[];
    /** Email address, unique per store */
    email: string;
    /** Links to records in other systems */
    external_references: string[];
    /** First name */
    first_name: string;
    /** Unique customer ID */
    id: number;
    /** Last name */
    last_name: string;
    /** Free form per customer data */
    metadata: Record<string, unknown>;
    /** Phone number, unique per store */
    phone: string;
    /** Total stamps across every card */
    stamp_count: number;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
