// This file was auto-generated by Fern from our API Definition.

export interface ListLocationsResponseItem {
    /** Parent store ID */
    account_id: number;
    /** Full street address */
    address: string;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Unique location ID */
    id: number;
    /** Geocoded latitude (auto-derived from address) */
    latitude: number;
    /** Geocoded longitude (auto-derived from address) */
    longitude: number;
    /** Location name (e.g. 'Downtown Branch') */
    name: string;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
