// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         card: {
 *             name: "name"
 *         }
 *     }
 */
export interface CreateCardsRequest {
    /** Parent store ID */
    account_id: number;
    card: CreateCardsRequest.Card;
}

export namespace CreateCardsRequest {
    export interface Card {
        /** Up to two extra front-of-pass fields. Blank values are ignored. */
        auxiliary_fields?: string[] | undefined;
        /** Hex colour for the card background (e.g. '#6B4226') */
        card_color?: string | undefined;
        /** Card expiry timestamp (ISO 8601) */
        expires_at?: string | undefined;
        /** Optional header text displayed on the card */
        header_text?: string | undefined;
        /** Number of stamps pre-filled on new customer cards (must be >= 0 and < stamps_required) */
        initial_stamps?: number | undefined;
        /** Card name (e.g. 'Coffee Loyalty Card') */
        name: string;
        /** Whether wallet passes show the member name field */
        show_member_field?: boolean | undefined;
        /** Whether wallet passes show the stamps-to-reward field */
        show_stamps_to_reward_field?: boolean | undefined;
        /** Hex colour for stamp backgrounds */
        stamp_background_color?: string | undefined;
        /** Hex colour for stamp icons */
        stamp_color?: string | undefined;
        /** Stamp icon identifier */
        stamp_icon?: string | undefined;
        /** Number of stamps needed to complete the card (1–21) */
        stamps_required?: number | undefined;
        /** Hex colour for the strip (used when strip_type is 'color') */
        strip_color?: string | undefined;
        /** Preset strip image identifier (used when strip_type is 'preset') */
        strip_preset?: string | undefined;
        /** Strip image type */
        strip_type?: string | undefined;
        /** Hex colour for card text */
        text_color?: string | undefined;
    }
}
