// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1
 *     }
 */
export interface GetCardsRequest {
    /** Parent store ID */
    account_id: number;
    /** Card ID */
    id: number;
}
