// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1
 *     }
 */
export interface ListCardsRequest {
    /** Parent store ID */
    account_id: number;
    /** Filter cards by archive status. Default: active only. */
    scope?: string;
}
