// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1,
 *         card: {}
 *     }
 */
export interface UpdateCardsRequest {
    /** Parent store ID */
    account_id: number;
    /** Card ID */
    id: number;
    card: UpdateCardsRequest.Card;
}

export namespace UpdateCardsRequest {
    export interface Card {
        /** Hex colour for the card background */
        card_color?: string | undefined;
        /** Optional header text displayed on the card */
        header_text?: string | undefined;
        /** Pre-filled stamps (must be >= 0 and < stamps_required) */
        initial_stamps?: number | undefined;
        /** Card name */
        name?: string | undefined;
        /** Hex colour for stamp backgrounds */
        stamp_background_color?: string | undefined;
        /** Hex colour for stamp icons */
        stamp_color?: string | undefined;
        /** Stamp icon identifier */
        stamp_icon?: string | undefined;
        /** Number of stamps needed (1–21) */
        stamps_required?: number | undefined;
        /** Hex colour for the strip */
        strip_color?: string | undefined;
        /** Preset strip image identifier */
        strip_preset?: string | undefined;
        /** Strip image type */
        strip_type?: string | undefined;
        /** Hex colour for card text */
        text_color?: string | undefined;
    }
}
