// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         reward: {
 *             card_id: 1,
 *             name: "name",
 *             stamps_required: 1
 *         }
 *     }
 */
export interface CreateRewardsRequest {
    /** Store (account) ID */
    account_id: number;
    reward: CreateRewardsRequest.Reward;
}

export namespace CreateRewardsRequest {
    export interface Reward {
        /** Whether the reward is active and redeemable (defaults to true) */
        active?: boolean | undefined;
        /** ID of the loyalty card this reward belongs to */
        card_id: number;
        /** Detailed description of the reward */
        description?: string | undefined;
        /** Display name of the reward (e.g. 'Free Coffee') */
        name: string;
        /** Display order position (lower numbers appear first) */
        position?: number | undefined;
        /** Number of stamps needed to unlock this reward (must be > 0) */
        stamps_required: number;
    }
}
