// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1
 *     }
 */
export interface DeleteRewardsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Reward ID */
    id: number;
}
