// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1
 *     }
 */
export interface ListRewardsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Filter rewards belonging to a specific card */
    card_id?: number;
    /** When present, return only active rewards */
    active?: string;
}
