// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1,
 *         reward: {}
 *     }
 */
export interface UpdateRewardsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Reward ID */
    id: number;
    reward: UpdateRewardsRequest.Reward;
}

export namespace UpdateRewardsRequest {
    export interface Reward {
        /** Whether the reward is active and redeemable */
        active?: boolean | undefined;
        /** Detailed description of the reward */
        description?: string | undefined;
        /** Display name of the reward */
        name?: string | undefined;
        /** Display order position */
        position?: number | undefined;
        /** Number of stamps needed to unlock this reward (must be > 0) */
        stamps_required?: number | undefined;
    }
}
