// This file was auto-generated by Fern from our API Definition.

export interface UpdateStoresResponse {
    /** Number of loyalty card templates */
    cards_count: number;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Number of enrolled customers */
    customers_count: number;
    /** Resolved display name (store_name if present, otherwise name) */
    display_store_name: string;
    /** Unique store ID */
    id: number;
    /** Number of physical locations */
    locations_count: number;
    /** Internal account name */
    name: string;
    /** Whether this is the user's personal account */
    personal: boolean;
    /** Number of QR signup posters */
    posters_count: number;
    /** Public-facing store name */
    store_name: string;
    /** ISO 8601 last-update timestamp */
    updated_at: string;
}
