// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         customer: {
 *             first_name: "first_name"
 *         }
 *     }
 */
export interface CreateCustomersRequest {
    /** Store (account) ID */
    account_id: number;
    /** Loyalty card ID to auto-enroll the customer in */
    card_id?: number;
    customer: CreateCustomersRequest.Customer;
    /** When true, sends the card links to the customer via email/SMS after enrollment. Note: even without this flag, the response includes `apple_wallet_url` and `google_wallet_url` in each customer card object so you can deliver them yourself. */
    send_card_links?: boolean;
}

export namespace CreateCustomersRequest {
    export interface Customer {
        /** Customer's birthday (YYYY-MM-DD) */
        birthday?: string | undefined;
        /** Customer's email address (unique per store; required if phone is blank) */
        email?: string | undefined;
        /** Array of `{source, external_id, metadata}` objects linking this customer to records in external systems */
        external_references?: string[] | undefined;
        /** Customer's first name */
        first_name: string;
        /** Customer's last name */
        last_name?: string | undefined;
        /** Free-form JSON object of additional per-customer attributes */
        metadata?: Record<string, unknown> | undefined;
        /** Customer's phone number (unique per store; required if email is blank) */
        phone?: string | undefined;
    }
}
