// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1
 *     }
 */
export interface ListCustomersRequest {
    /** Store (account) ID */
    account_id: number;
    /** Search query to filter customers by name, email, phone, card code (barcode), or external reference ID */
    search?: string;
    /** External system slug (e.g. `square`, `shopify`). When combined with `external_id`, performs an exact lookup. */
    source?: string;
    /** External system's identifier for the customer. Must be combined with `source`. */
    external_id?: string;
    /** Page number (defaults to 1) */
    page?: number;
    /** Number of items per page */
    items?: number;
}
