// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1,
 *         customer: {}
 *     }
 */
export interface UpdateCustomersRequest {
    /** Store (account) ID */
    account_id: number;
    /** Customer ID */
    id: number;
    customer: UpdateCustomersRequest.Customer;
}

export namespace UpdateCustomersRequest {
    export interface Customer {
        /** Customer's birthday (YYYY-MM-DD) */
        birthday?: string | undefined;
        /** Customer's email address (unique per store) */
        email?: string | undefined;
        /** Array of `{source, external_id, metadata}` objects to upsert */
        external_references?: string[] | undefined;
        /** Customer's first name */
        first_name?: string | undefined;
        /** Customer's last name */
        last_name?: string | undefined;
        /** Shallow-merged into existing metadata */
        metadata?: Record<string, unknown> | undefined;
        /** Customer's phone number (unique per store) */
        phone?: string | undefined;
    }
}
