// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1
 *     }
 */
export interface GetApiV1AccountsAccountIdWebhookSubscriptionsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Only return subscriptions that list this event (or `*`) */
    event?: string;
}
