// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         id: 1
 *     }
 */
export interface PatchApiV1AccountsAccountIdWebhookSubscriptionsIdRequest {
    /** Store (account) ID */
    account_id: number;
    /** Webhook subscription ID */
    id: number;
    /** Your own label, up to 255 characters */
    description?: string;
    /** false to pause deliveries, true to resume them */
    enabled?: boolean;
    /** A single event. Same as `events` with one entry */
    event?: string;
    /** Replaces the list of events, or `["*"]` for every event */
    events?: string[];
    /** `envelope` or `flat` */
    payload_format?: string;
    /** Public https URL that will receive the POST requests */
    target_url?: string;
}
