// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: 1,
 *         target_url: "target_url"
 *     }
 */
export interface PostApiV1AccountsAccountIdWebhookSubscriptionsRequest {
    /** Store (account) ID */
    account_id: number;
    /** Your own label, up to 255 characters */
    description?: string;
    /** Create the subscription disabled by passing false (defaults to true) */
    enabled?: boolean;
    /** A single event to subscribe to. Same as `events` with one entry */
    event?: string;
    /** Events to subscribe to, or `["*"]` for every event. Required unless `event` is given */
    events?: string[];
    /** `envelope` (default) or `flat`. `flat` sends the bare data object and cannot be combined with `*` */
    payload_format?: string;
    /** Public https URL that will receive the POST requests */
    target_url: string;
}
