// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { customers: ["customers"], pagination: { count: 1, items: 1, page: 1, pages: 1 } };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customers.list({
            account_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {
            account_id: 1,
            birthday: "birthday",
            created_at: "created_at",
            customer_cards: ["customer_cards"],
            email: "email",
            external_references: ["external_references"],
            first_name: "first_name",
            id: 1,
            last_name: "last_name",
            metadata: { key: "value" },
            phone: "phone",
            stamp_count: 1,
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customers.create({
            account_id: 1,
            customer: {
                first_name: "first_name",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.create({
                account_id: 1,
                customer: {
                    first_name: "first_name",
                },
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.create({
                account_id: 1,
                customer: {
                    first_name: "first_name",
                },
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.create({
                account_id: 1,
                customer: {
                    first_name: "first_name",
                },
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.create({
                account_id: 1,
                customer: {
                    first_name: "first_name",
                },
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: { first_name: "first_name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.create({
                account_id: 1,
                customer: {
                    first_name: "first_name",
                },
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            birthday: "birthday",
            created_at: "created_at",
            customer_cards: ["customer_cards"],
            email: "email",
            external_references: ["external_references"],
            first_name: "first_name",
            id: 1,
            last_name: "last_name",
            metadata: { key: "value" },
            phone: "phone",
            stamp_count: 1,
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customers.get({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {
            account_id: 1,
            birthday: "birthday",
            created_at: "created_at",
            customer_cards: ["customer_cards"],
            email: "email",
            external_references: ["external_references"],
            first_name: "first_name",
            id: 1,
            last_name: "last_name",
            metadata: { key: "value" },
            phone: "phone",
            stamp_count: 1,
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customers.update({
            account_id: 1,
            id: 1,
            customer: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.update({
                account_id: 1,
                id: 1,
                customer: {},
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.update({
                account_id: 1,
                id: 1,
                customer: {},
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.update({
                account_id: 1,
                id: 1,
                customer: {},
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.update({
                account_id: 1,
                id: 1,
                customer: {},
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { customer: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/customers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customers.update({
                account_id: 1,
                id: 1,
                customer: {},
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
