// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomerCardsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                apple_wallet_url: "apple_wallet_url",
                card_id: 1,
                card_name: "card_name",
                created_at: "created_at",
                google_wallet_url: "google_wallet_url",
                id: 1,
                issued_at: "issued_at",
                pass_installed: true,
                progress_percentage: 1.1,
                stamps_count: 1,
                stamps_remaining: 1,
                status: "status",
                updated_at: "updated_at",
                uuid: "uuid",
            },
        ];

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customerCards.list({
            account_id: 1,
            customer_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.list({
                account_id: 1,
                customer_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.list({
                account_id: 1,
                customer_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.list({
                account_id: 1,
                customer_id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.list({
                account_id: 1,
                customer_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            apple_wallet_url: "apple_wallet_url",
            available_rewards: ["available_rewards"],
            card_id: 1,
            card_name: "card_name",
            created_at: "created_at",
            customer_id: 1,
            google_wallet_url: "google_wallet_url",
            id: 1,
            issued_at: "issued_at",
            pass_installed: true,
            progress_percentage: 1.1,
            stamps_count: 1,
            stamps_remaining: 1,
            status: "status",
            updated_at: "updated_at",
            uuid: "uuid",
        };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customerCards.get({
            account_id: 1,
            customer_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.get({
                account_id: 1,
                customer_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.get({
                account_id: 1,
                customer_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.get({
                account_id: 1,
                customer_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/customers/1/customer_cards/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.get({
                account_id: 1,
                customer_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("redeem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {
            redemption: {
                id: 1,
                redeemed_at: "redeemed_at",
                reward_id: 1,
                reward_name: "reward_name",
                stamps_remaining: 1,
                stamps_spent: 1,
            },
            success: true,
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customerCards.redeem({
            account_id: 1,
            customer_id: 1,
            id: 1,
            reward_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("redeem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.redeem({
                account_id: 1,
                customer_id: 1,
                id: 1,
                reward_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("redeem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.redeem({
                account_id: 1,
                customer_id: 1,
                id: 1,
                reward_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("redeem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.redeem({
                account_id: 1,
                customer_id: 1,
                id: 1,
                reward_id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("redeem (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.redeem({
                account_id: 1,
                customer_id: 1,
                id: 1,
                reward_id: 1,
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("redeem (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { reward_id: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/redeem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.redeem({
                account_id: 1,
                customer_id: 1,
                id: 1,
                reward_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("stamp (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {
            account_id: 1,
            apple_wallet_url: "apple_wallet_url",
            available_rewards: ["available_rewards"],
            card_id: 1,
            card_name: "card_name",
            created_at: "created_at",
            customer_id: 1,
            google_wallet_url: "google_wallet_url",
            id: 1,
            issued_at: "issued_at",
            pass_installed: true,
            progress_percentage: 1.1,
            stamps_count: 1,
            stamps_remaining: 1,
            status: "status",
            updated_at: "updated_at",
            uuid: "uuid",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customerCards.stamp({
            account_id: 1,
            customer_id: 1,
            id: 1,
            stamps: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("stamp (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.stamp({
                account_id: 1,
                customer_id: 1,
                id: 1,
                stamps: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("stamp (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.stamp({
                account_id: 1,
                customer_id: 1,
                id: 1,
                stamps: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("stamp (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.stamp({
                account_id: 1,
                customer_id: 1,
                id: 1,
                stamps: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("stamp (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.stamp({
                account_id: 1,
                customer_id: 1,
                id: 1,
                stamps: 1,
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("stamp (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { stamps: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/customers/1/customer_cards/1/stamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customerCards.stamp({
                account_id: 1,
                customer_id: 1,
                id: 1,
                stamps: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
