// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("LocationsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                account_id: 1,
                address: "address",
                created_at: "created_at",
                id: 1,
                latitude: 1.1,
                longitude: 1.1,
                name: "name",
                updated_at: "updated_at",
            },
        ];

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.locations.list({
            account_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {
            account_id: 1,
            address: "address",
            created_at: "created_at",
            id: 1,
            latitude: 1.1,
            longitude: 1.1,
            name: "name",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.locations.create({
            account_id: 1,
            location: {
                address: "address",
                name: "name",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.create({
                account_id: 1,
                location: {
                    address: "address",
                    name: "name",
                },
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.create({
                account_id: 1,
                location: {
                    address: "address",
                    name: "name",
                },
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.create({
                account_id: 1,
                location: {
                    address: "address",
                    name: "name",
                },
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.create({
                account_id: 1,
                location: {
                    address: "address",
                    name: "name",
                },
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: { address: "address", name: "name" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/locations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.create({
                account_id: 1,
                location: {
                    address: "address",
                    name: "name",
                },
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            address: "address",
            created_at: "created_at",
            id: 1,
            latitude: 1.1,
            longitude: 1.1,
            name: "name",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.locations.get({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/accounts/1/locations/1").respondWith().statusCode(200).build();

        const response = await client.locations.delete({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/locations/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {
            account_id: 1,
            address: "address",
            created_at: "created_at",
            id: 1,
            latitude: 1.1,
            longitude: 1.1,
            name: "name",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.locations.update({
            account_id: 1,
            id: 1,
            location: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.update({
                account_id: 1,
                id: 1,
                location: {},
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.update({
                account_id: 1,
                id: 1,
                location: {},
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.update({
                account_id: 1,
                id: 1,
                location: {},
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.update({
                account_id: 1,
                id: 1,
                location: {},
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { location: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/locations/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.locations.update({
                account_id: 1,
                id: 1,
                location: {},
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
