// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PostersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                account_id: 1,
                active: true,
                card_id: 1,
                created_at: "created_at",
                display_url: "display_url",
                id: 1,
                paper_size: "paper_size",
                primary_color: "primary_color",
                qr_code_url: "qr_code_url",
                secondary_color: "secondary_color",
                signup_url: "signup_url",
                text_color: "text_color",
                title: "title",
                updated_at: "updated_at",
            },
        ];

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.posters.list({
            account_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.list({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: { card_id: 1 } };
        const rawResponseBody = {
            account_id: 1,
            active: true,
            card_id: 1,
            created_at: "created_at",
            display_url: "display_url",
            id: 1,
            paper_size: "paper_size",
            primary_color: "primary_color",
            qr_code_url: "qr_code_url",
            secondary_color: "secondary_color",
            signup_url: "signup_url",
            text_color: "text_color",
            title: "title",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/posters")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.posters.create({
            account_id: 1,
            poster: {
                card_id: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: { card_id: 1 } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/posters")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.create({
                account_id: 1,
                poster: {
                    card_id: 1,
                },
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: { card_id: 1 } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/posters")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.create({
                account_id: 1,
                poster: {
                    card_id: 1,
                },
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: { card_id: 1 } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/posters")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.create({
                account_id: 1,
                poster: {
                    card_id: 1,
                },
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: { card_id: 1 } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/posters")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.create({
                account_id: 1,
                poster: {
                    card_id: 1,
                },
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            active: true,
            card_id: 1,
            created_at: "created_at",
            display_url: "display_url",
            id: 1,
            paper_size: "paper_size",
            primary_color: "primary_color",
            qr_code_url: "qr_code_url",
            secondary_color: "secondary_color",
            signup_url: "signup_url",
            text_color: "text_color",
            title: "title",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.posters.get({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.get({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/accounts/1/posters/1").respondWith().statusCode(200).build();

        const response = await client.posters.delete({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/posters/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.delete({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: {} };
        const rawResponseBody = {
            account_id: 1,
            active: true,
            card_id: 1,
            created_at: "created_at",
            display_url: "display_url",
            id: 1,
            paper_size: "paper_size",
            primary_color: "primary_color",
            qr_code_url: "qr_code_url",
            secondary_color: "secondary_color",
            signup_url: "signup_url",
            text_color: "text_color",
            title: "title",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/posters/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.posters.update({
            account_id: 1,
            id: 1,
            poster: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/posters/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.update({
                account_id: 1,
                id: 1,
                poster: {},
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/posters/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.update({
                account_id: 1,
                id: 1,
                poster: {},
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/posters/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.update({
                account_id: 1,
                id: 1,
                poster: {},
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { poster: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/posters/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.posters.update({
                account_id: 1,
                id: 1,
                poster: {},
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
