// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("StatusClient", () => {
    test("check (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            api_version: "api_version",
            authentication: "authentication",
            developer_portal_url: "developer_portal_url",
            documentation_url: "documentation_url",
            openapi_url: "openapi_url",
            rate_limit: { limit: 1, scope: "scope", window_seconds: 1 },
            status: "status",
        };

        server.mockEndpoint().get("/api/v1/status").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.status.check();
        expect(response).toEqual(rawResponseBody);
    });

    test("check (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/status").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.status.check();
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
