// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("StoresClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                cards_count: 1,
                created_at: "created_at",
                customers_count: 1,
                display_store_name: "display_store_name",
                id: 1,
                locations_count: 1,
                name: "name",
                personal: true,
                posters_count: 1,
                store_name: "store_name",
                updated_at: "updated_at",
            },
        ];

        server.mockEndpoint().get("/api/v1/accounts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.stores.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/accounts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.stores.list();
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/accounts").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.stores.list();
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            cards_count: 1,
            created_at: "created_at",
            customers_count: 1,
            display_store_name: "display_store_name",
            id: 1,
            locations_count: 1,
            name: "name",
            personal: true,
            posters_count: 1,
            store_name: "store_name",
            updated_at: "updated_at",
        };

        server.mockEndpoint().get("/api/v1/accounts/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.stores.get({
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/accounts/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.stores.get({
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/accounts/1").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.stores.get({
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/v1/accounts/1").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.stores.get({
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { account: {} };
        const rawResponseBody = {
            cards_count: 1,
            created_at: "created_at",
            customers_count: 1,
            display_store_name: "display_store_name",
            id: 1,
            locations_count: 1,
            name: "name",
            personal: true,
            posters_count: 1,
            store_name: "store_name",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.stores.update({
            id: 1,
            account: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { account: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.stores.update({
                id: 1,
                account: {},
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { account: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.stores.update({
                id: 1,
                account: {},
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { account: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.stores.update({
                id: 1,
                account: {},
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { account: {} };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.stores.update({
                id: 1,
                account: {},
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
