// This file was auto-generated by Fern from our API Definition.

import * as Leal from "../../src/api/index";
import { LealClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhookSubscriptionsClient", () => {
    test("get_api_v1_accounts_account_id_webhook_subscriptions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                account_id: 1,
                created_at: "created_at",
                description: "description",
                disabled_at: "disabled_at",
                disabled_reason: "disabled_reason",
                enabled: true,
                event: "event",
                events: ["events"],
                id: 1,
                last_delivery_at: "last_delivery_at",
                last_delivery_error: "last_delivery_error",
                last_delivery_status: 1.1,
                payload_format: "payload_format",
                target_url: "target_url",
                updated_at: "updated_at",
            },
        ];

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
            account_id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {
            account_id: 1,
            created_at: "created_at",
            description: "description",
            disabled_at: "disabled_at",
            disabled_reason: "disabled_reason",
            enabled: true,
            event: "event",
            events: ["events"],
            id: 1,
            last_delivery_at: "last_delivery_at",
            last_delivery_error: "last_delivery_error",
            last_delivery_status: 1.1,
            payload_format: "payload_format",
            secret: "secret",
            target_url: "target_url",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
            account_id: 1,
            target_url: "target_url",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
                target_url: "target_url",
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
                target_url: "target_url",
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
                target_url: "target_url",
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
                target_url: "target_url",
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { target_url: "target_url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptions({
                account_id: 1,
                target_url: "target_url",
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions_id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            created_at: "created_at",
            description: "description",
            disabled_at: "disabled_at",
            disabled_reason: "disabled_reason",
            enabled: true,
            event: "event",
            events: ["events"],
            id: 1,
            last_delivery_at: "last_delivery_at",
            last_delivery_error: "last_delivery_error",
            last_delivery_status: 1.1,
            payload_format: "payload_format",
            secret: "secret",
            target_url: "target_url",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions_id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions_id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions_id (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("get_api_v1_accounts_account_id_webhook_subscriptions_id (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.getApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("delete_api_v1_accounts_account_id_webhook_subscriptions_id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("delete_api_v1_accounts_account_id_webhook_subscriptions_id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("delete_api_v1_accounts_account_id_webhook_subscriptions_id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("delete_api_v1_accounts_account_id_webhook_subscriptions_id (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("delete_api_v1_accounts_account_id_webhook_subscriptions_id (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/accounts/1/webhook_subscriptions/1")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.deleteApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            account_id: 1,
            created_at: "created_at",
            description: "description",
            disabled_at: "disabled_at",
            disabled_reason: "disabled_reason",
            enabled: true,
            event: "event",
            events: ["events"],
            id: 1,
            last_delivery_at: "last_delivery_at",
            last_delivery_error: "last_delivery_error",
            last_delivery_status: 1.1,
            payload_format: "payload_format",
            target_url: "target_url",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnprocessableEntityError);
    });

    test("patch_api_v1_accounts_account_id_webhook_subscriptions_id (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api/v1/accounts/1/webhook_subscriptions/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.patchApiV1AccountsAccountIdWebhookSubscriptionsId({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_rotate_secret (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_id: 1,
            created_at: "created_at",
            description: "description",
            disabled_at: "disabled_at",
            disabled_reason: "disabled_reason",
            enabled: true,
            event: "event",
            events: ["events"],
            id: 1,
            last_delivery_at: "last_delivery_at",
            last_delivery_error: "last_delivery_error",
            last_delivery_status: 1.1,
            payload_format: "payload_format",
            secret: "secret",
            target_url: "target_url",
            updated_at: "updated_at",
        };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/rotate_secret")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret(
            {
                account_id: 1,
                id: 1,
            },
        );
        expect(response).toEqual(rawResponseBody);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_rotate_secret (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/rotate_secret")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_rotate_secret (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/rotate_secret")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_rotate_secret (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/rotate_secret")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_rotate_secret (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/rotate_secret")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdRotateSecret({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_test (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { delivered: true, error: "error", event_id: "event_id", status: 1.1 };

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/test")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
            account_id: 1,
            id: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_test (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/test")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.UnauthorizedError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_test (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/test")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.NotFoundError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_test (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/test")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.GoneError);
    });

    test("post_api_v1_accounts_account_id_webhook_subscriptions_id_test (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new LealClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/accounts/1/webhook_subscriptions/1/test")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhookSubscriptions.postApiV1AccountsAccountIdWebhookSubscriptionsIdTest({
                account_id: 1,
                id: 1,
            });
        }).rejects.toThrow(Leal.TooManyRequestsError);
    });
});
