// This file was auto-generated by Fern from our API Definition.

import { CardsClient } from "./api/resources/cards/client/Client.js";
import { CustomerCardsClient } from "./api/resources/customerCards/client/Client.js";
import { CustomersClient } from "./api/resources/customers/client/Client.js";
import { LocationsClient } from "./api/resources/locations/client/Client.js";
import { PostersClient } from "./api/resources/posters/client/Client.js";
import { RewardsClient } from "./api/resources/rewards/client/Client.js";
import { StatusClient } from "./api/resources/status/client/Client.js";
import { StoresClient } from "./api/resources/stores/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace LealClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LealClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LealClient.Options>;
    protected _stores: StoresClient | undefined;
    protected _cards: CardsClient | undefined;
    protected _customers: CustomersClient | undefined;
    protected _customerCards: CustomerCardsClient | undefined;
    protected _locations: LocationsClient | undefined;
    protected _posters: PostersClient | undefined;
    protected _rewards: RewardsClient | undefined;
    protected _status: StatusClient | undefined;

    constructor(options: LealClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get stores(): StoresClient {
        return (this._stores ??= new StoresClient(this._options));
    }

    public get cards(): CardsClient {
        return (this._cards ??= new CardsClient(this._options));
    }

    public get customers(): CustomersClient {
        return (this._customers ??= new CustomersClient(this._options));
    }

    public get customerCards(): CustomerCardsClient {
        return (this._customerCards ??= new CustomerCardsClient(this._options));
    }

    public get locations(): LocationsClient {
        return (this._locations ??= new LocationsClient(this._options));
    }

    public get posters(): PostersClient {
        return (this._posters ??= new PostersClient(this._options));
    }

    public get rewards(): RewardsClient {
        return (this._rewards ??= new RewardsClient(this._options));
    }

    public get status(): StatusClient {
        return (this._status ??= new StatusClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
