// This file was auto-generated by Fern from our API Definition.

export const LealEnvironment = {
    Production: "https://app.getleal.com",
} as const;

export type LealEnvironment = typeof LealEnvironment.Production;
