// This file was auto-generated by Fern from our API Definition.

export interface CheckStatusResponse {
    /** Current API version */
    api_version: string;
    /** How to authenticate a request */
    authentication: string;
    /** Developer portal: quickstart, auth, webhooks */
    developer_portal_url: string;
    /** Human readable API reference */
    documentation_url: string;
    /** OpenAPI description of this API */
    openapi_url: string;
    rate_limit: CheckStatusResponse.RateLimit;
    /** 'ok' while the API is serving requests */
    status: string;
    versioning: CheckStatusResponse.Versioning;
}

export namespace CheckStatusResponse {
    export interface RateLimit {
        /** Requests allowed per window */
        limit: number;
        /** What the limit is counted against */
        scope: string;
        /** Length of the window in seconds */
        window_seconds: number;
    }

    export interface Versioning {
        /** The version to build against */
        current: string;
        /** Versions that are deprecated but still serving */
        deprecated: string[];
        /** The published versioning and deprecation policy */
        policy_url: string;
        /** The headers a deprecated version sends */
        signalling: string;
        /** Every version still serving requests */
        supported: string[];
    }
}
