// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1,
 *         account: {}
 *     }
 */
export interface UpdateStoresRequest {
    /** Store ID */
    id: number;
    account: UpdateStoresRequest.Account;
}

export namespace UpdateStoresRequest {
    export interface Account {
        /** Internal account name */
        name?: string | undefined;
        /** Public-facing store name shown to customers */
        store_name?: string | undefined;
    }
}
